# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/early.xdc

# XDC: imports/constraints/normal.xdc

# Block Designs: bd/Top/Top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top || ORIG_REF_NAME==Top} -quiet] -quiet

# IP: bd/Top/ip/Top_Model_0/Top_Model_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_Model_0 || ORIG_REF_NAME==Top_Model_0} -quiet] -quiet

# IP: bd/Top/ip/Top_Version_0/Top_Version_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_Version_0 || ORIG_REF_NAME==Top_Version_0} -quiet] -quiet

# IP: bd/Top/ip/Top_xlslice_0_0/Top_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_xlslice_0_0 || ORIG_REF_NAME==Top_xlslice_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_gpio_0_0/Top_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_axi_gpio_0_0 || ORIG_REF_NAME==Top_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_gpio_1_0/Top_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_axi_gpio_1_0 || ORIG_REF_NAME==Top_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_gpio_2_0/Top_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_axi_gpio_2_0 || ORIG_REF_NAME==Top_axi_gpio_2_0} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_interconnect_1_upgraded_ipi_imp_xbar_0/Top_axi_interconnect_1_upgraded_ipi_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_axi_interconnect_1_upgraded_ipi_imp_xbar_0 || ORIG_REF_NAME==Top_axi_interconnect_1_upgraded_ipi_imp_xbar_0} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_interconnect_1_0/Top_axi_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_axi_interconnect_1_0 || ORIG_REF_NAME==Top_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/Top/ip/Top_c_counter_binary_0_0/Top_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_c_counter_binary_0_0 || ORIG_REF_NAME==Top_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_dna_reader_0_0/Top_dna_reader_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_dna_reader_0_0 || ORIG_REF_NAME==Top_dna_reader_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_user_efuse_0_0/Top_user_efuse_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_user_efuse_0_0 || ORIG_REF_NAME==Top_user_efuse_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_mig_7series_0_0/Top_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_mig_7series_0_0 || ORIG_REF_NAME==Top_mig_7series_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_xlconstant_1_0/Top_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_xlconstant_1_0 || ORIG_REF_NAME==Top_xlconstant_1_0} -quiet] -quiet

# IP: bd/Top/ip/Top_xlconstant_2_0/Top_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_xlconstant_2_0 || ORIG_REF_NAME==Top_xlconstant_2_0} -quiet] -quiet

# IP: bd/Top/ip/Top_xlslice_0_3/Top_xlslice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_xlslice_0_3 || ORIG_REF_NAME==Top_xlslice_0_3} -quiet] -quiet

# IP: bd/Top/ip/Top_xadc_wiz_1_0/Top_xadc_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_xadc_wiz_1_0 || ORIG_REF_NAME==Top_xadc_wiz_1_0} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_interconnect_0_upgraded_ipi_imp_xbar_0/Top_axi_interconnect_0_upgraded_ipi_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_axi_interconnect_0_upgraded_ipi_imp_xbar_0 || ORIG_REF_NAME==Top_axi_interconnect_0_upgraded_ipi_imp_xbar_0} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_interconnect_0_0/Top_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_axi_interconnect_0_0 || ORIG_REF_NAME==Top_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_interconnect_1_1/Top_axi_interconnect_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_axi_interconnect_1_1 || ORIG_REF_NAME==Top_axi_interconnect_1_1} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_quad_spi_0_0/Top_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_axi_quad_spi_0_0 || ORIG_REF_NAME==Top_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_util_ds_buf_0/Top_util_ds_buf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_util_ds_buf_0 || ORIG_REF_NAME==Top_util_ds_buf_0} -quiet] -quiet

# IP: bd/Top/ip/Top_util_vector_logic_0_2/Top_util_vector_logic_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_util_vector_logic_0_2 || ORIG_REF_NAME==Top_util_vector_logic_0_2} -quiet] -quiet

# IP: bd/Top/ip/Top_xdma_0_0/Top_xdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_xdma_0_0 || ORIG_REF_NAME==Top_xdma_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_const_true_1/Top_const_true_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_const_true_1 || ORIG_REF_NAME==Top_const_true_1} -quiet] -quiet

# IP: bd/Top/ip/Top_CodeBlinker_0_3/Top_CodeBlinker_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_CodeBlinker_0_3 || ORIG_REF_NAME==Top_CodeBlinker_0_3} -quiet] -quiet

# IP: bd/Top/ip/Top_xlslice_0_4/Top_xlslice_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_xlslice_0_4 || ORIG_REF_NAME==Top_xlslice_0_4} -quiet] -quiet

# IP: bd/Top/ip/Top_xlslice_1_0/Top_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_xlslice_1_0 || ORIG_REF_NAME==Top_xlslice_1_0} -quiet] -quiet

# IP: bd/Top/ip/Top_xlconstant_0_1/Top_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_xlconstant_0_1 || ORIG_REF_NAME==Top_xlconstant_0_1} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_interconnect_1_imp_auto_cc_0/Top_axi_interconnect_1_imp_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_axi_interconnect_1_imp_auto_cc_0 || ORIG_REF_NAME==Top_axi_interconnect_1_imp_auto_cc_0} -quiet] -quiet

# XDC: c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/Top_ooc.xdc
