# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/fpga/pnvme/pnvme/pnvme.runs/synth_1/Top_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_msg_config  -id {DRC NSTD-1}  -string {{ERROR: [DRC NSTD-1] Unspecified I/O Standard: 6 out of 6 logical ports use I/O standard (IOSTANDARD) value 'DEFAULT', instead of a user assigned specific value. This may cause I/O contention or incompatibility with the board power or connectivity affecting performance, signal integrity or in extreme cases cause damage to the device or the components to which it is connected. To correct this violation, specify all I/O standards. This design will fail to generate a bitstream unless all logical ports have a user specified I/O standard value defined. To allow bitstream creation with unspecified I/O standard values (not recommended), use this command: set_property SEVERITY {Warning} [get_drc_checks NSTD-1].  NOTE: When using the Vivado Runs infrastructure (e.g. launch_runs Tcl command), add this command to a .tcl file and add that file as a pre-hook for write_bitstream step for the implementation run. Problem ports: code[2:0], clk, led, and ok.}}  -suppress 
set_msg_config  -id {DRC UCIO-1}  -string {{ERROR: [DRC UCIO-1] Unconstrained Logical Port: 6 out of 6 logical ports have no user assigned specific location constraint (LOC). This may cause I/O contention or incompatibility with the board power or connectivity affecting performance, signal integrity or in extreme cases cause damage to the device or the components to which it is connected. To correct this violation, specify all pin locations. This design will fail to generate a bitstream unless all logical ports have a user specified site LOC constraint defined.  To allow bitstream creation with unspecified pin locations (not recommended), use this command: set_property SEVERITY {Warning} [get_drc_checks UCIO-1].  NOTE: When using the Vivado Runs infrastructure (e.g. launch_runs Tcl command), add this command to a .tcl file and add that file as a pre-hook for write_bitstream step for the implementation run.  Problem ports: code[2:0], clk, led, and ok.}}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tfgg484-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/fpga/pnvme/pnvme/pnvme.cache/wt [current_project]
set_property parent.project_path C:/fpga/pnvme/pnvme/pnvme.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/fpga/pnvme/nvmebar_ip
  c:/fpga/pnvme/ip_repo
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/fpga/pnvme/pnvme/pnvme.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib C:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/hdl/Top_wrapper.v
add_files C:/fpga/pnvme/pnvme/pnvme.srcs/sources_1/bd/Top/Top.bd
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_axi_gpio_0_0/Top_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_axi_gpio_0_0/Top_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_axi_gpio_1_0/Top_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_axi_gpio_1_0/Top_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_axi_gpio_2_0/Top_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_axi_gpio_2_0/Top_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_axi_interconnect_1_upgraded_ipi_imp_xbar_0/Top_axi_interconnect_1_upgraded_ipi_imp_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_c_counter_binary_0_0/Top_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_mig_7series_0_0/Top_mig_7series_0_0/user_design/constraints/Top_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_mig_7series_0_0/Top_mig_7series_0_0/user_design/constraints/Top_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_xadc_wiz_1_0/Top_xadc_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_xadc_wiz_1_0/Top_xadc_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_axi_interconnect_0_upgraded_ipi_imp_xbar_0/Top_axi_interconnect_0_upgraded_ipi_imp_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_axi_quad_spi_0_0/Top_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_axi_quad_spi_0_0/Top_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_axi_quad_spi_0_0/Top_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_axi_quad_spi_0_0/Top_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_util_ds_buf_0/Top_util_ds_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_util_ds_buf_0/Top_util_ds_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_xdma_0_0/ip_4/pcie2_fifo_generator_tgt_brdg.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_xdma_0_0/ip_3/pcie2_fifo_generator_dma_cpl.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_xdma_0_0/ip_2/xdma_v4_2_0_blk_mem_64_noreg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_xdma_0_0/ip_1/xdma_v4_2_0_blk_mem_64_reg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_xdma_0_0/ip_0/source/Top_xdma_0_0_pcie2_ip-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_xdma_0_0/ip_0/source/ip_xilinx_pcie_2_1_7x_late.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_xdma_0_0/ip_0/synth/Top_xdma_0_0_pcie2_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_xdma_0_0/Top_xdma_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_xdma_0_0/source/Top_xdma_0_0_pcie3_7vx_ip.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_xdma_0_0/synth/Top_xdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_axi_interconnect_0_imp_s00_mmu_0/Top_axi_interconnect_0_imp_s00_mmu_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_axi_interconnect_1_imp_auto_cc_0/Top_axi_interconnect_1_imp_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_axi_interconnect_1_imp_auto_cc_0/Top_axi_interconnect_1_imp_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_axi_interconnect_1_imp_auto_cc_0/Top_axi_interconnect_1_imp_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/Top_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/fpga/pnvme/pnvme/pnvme.srcs/constrs_1/imports/constraints/early.xdc
set_property used_in_implementation false [get_files C:/fpga/pnvme/pnvme/pnvme.srcs/constrs_1/imports/constraints/early.xdc]
set_property processing_order EARLY [get_files C:/fpga/pnvme/pnvme/pnvme.srcs/constrs_1/imports/constraints/early.xdc]

read_xdc C:/fpga/pnvme/pnvme/pnvme.srcs/constrs_1/imports/constraints/normal.xdc
set_property used_in_implementation false [get_files C:/fpga/pnvme/pnvme/pnvme.srcs/constrs_1/imports/constraints/normal.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Top_wrapper -part xc7a100tfgg484-2L
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file Top_wrapper_utilization_synth.rpt -pb Top_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
