# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/fpga/pnvme/pnvme/pnvme.srcs/sources_1/bd/Top/ip/Top_axi_interconnect_0_imp_s00_mmu_0/Top_axi_interconnect_0_imp_s00_mmu_0.xci
# IP: The module: 'Top_axi_interconnect_0_imp_s00_mmu_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_axi_interconnect_0_imp_s00_mmu_0/Top_axi_interconnect_0_imp_s00_mmu_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_axi_interconnect_0_imp_s00_mmu_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/fpga/pnvme/pnvme/pnvme.srcs/sources_1/bd/Top/ip/Top_axi_interconnect_0_imp_s00_mmu_0/Top_axi_interconnect_0_imp_s00_mmu_0.xci
# IP: The module: 'Top_axi_interconnect_0_imp_s00_mmu_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/fpga/pnvme/pnvme/pnvme.gen/sources_1/bd/Top/ip/Top_axi_interconnect_0_imp_s00_mmu_0/Top_axi_interconnect_0_imp_s00_mmu_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_axi_interconnect_0_imp_s00_mmu_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
